name: AdvancedBlockProtect
version: 1.0
main: de.jakomi1.advancedBlockProtect.Main
api-version: 1.21
commands:
  advancedblockprotect:
    description: Hauptbefehl für AdvancedBlockProtect
    usage: /<command>
